micronaut:
  application:
    name: metrics-calculator

rabbitmq:
  uri: amqp://localhost:5672

mongodb:
  uri: mongodb://localhost:27017

database: "laa"

event:
  exchange: nps-laa
  queue: access-logs
  routingKey: npa-access-logs