micronaut:
  application:
    name: nps-laa-ingest-service
  server:
    port: -1

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    status:
      http-mapping:
        DONW: 500

mongodb:
  uri: mongodb://localhost:27017

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"