micronaut:
  application:
    name: nps-laa

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    status:
      http-mapping:
        DONW: 500

mongodb:
  uri: mongodb://localhost:27017
